# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target '3Dify' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3Dify
  pod 'LTMorphingLabel'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint'
  pod 'R.swift'

end
